// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shuapssxrbgevinoetfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNodWFwc3N4cmJnZXZpbm9ldGZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MDAzNTksImV4cCI6MjA1NDQ3NjM1OX0.ED1bdvNZF54tYeAwjibVshSwL3Efp10o0_mEDN5j8BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);